services:
  # 1. アプリケーション用コンテナ
  app:
    # 下で作成するDockerfileをビルドして使用する
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # コンテナを起動し続けるためのコマンド
    command: sleep infinity
    # ソースコードをコンテナ内にマウント
    volumes:
      - ..:/workspace:cached
    # データベースへの接続情報
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      MINIO_ENDPOINT: http://minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: root_user
      MINIO_SECRET_KEY: root_password
      MINIO_BUCKET_NAME: nest-bucket 
    # dbサービスが起動してからappを起動する
    depends_on:
      - db
      - minio
    networks:
      - backend-network
    ports:
      - "3000:3000"

  # 2. データベース用コンテナ
  db:
    image: postgres:16 # PostgreSQLの公式イメージを使用
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend-network

  minio:
    image: minio/minio
    ports:
      # Webコンソール用のポート (ブラウザでアクセス)
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root_user
      - MINIO_ROOT_PASSWORD=root_password
    volumes:
      - minio_data:/data # データを永続化するためのボリューム
    command: server /data --console-address ":9001"
    networks:
      - backend-network

# データベースのデータを永続化するためのボリューム
volumes:
  postgres_data:
  minio_data:

networks:
  backend-network:
    driver: bridge