services:
  # 1. アプリケーション用コンテナ
  app:
    # 下で作成するDockerfileをビルドして使用する
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # コンテナを起動し続けるためのコマンド
    command: sleep infinity
    # ソースコードをコンテナ内にマウント
    volumes:
      - ..:/workspace:cached
    # データベースへの接続情報
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    # dbサービスが起動してからappを起動する
    depends_on:
      - db

  # 2. データベース用コンテナ
  db:
    image: postgres:16 # PostgreSQLの公式イメージを使用
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

# データベースのデータを永続化するためのボリューム
volumes:
  postgres_data: